### ISSUE TITLE
CSRF token support

### ISSUE THREAD

**Issue by kasongoyo** [lykmapipo/irina#17]
If i want to add cookie authentication in my app and introduce CSRF token as the way to improve security with my cookie then i have to do all that work separately while it could be nice if this module could support that. Only two process that is CSRF token generation and storage(CSRF token must be verifiable on the server).

**Comment by lykmapipo** [comment]
@kasongoyo 

irina its just a layer on top of mongoose. HTTP related logics will not be added. Consult passportjs or other libraries that offer HTTP layer.
