### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by maticrivo** [lykmapipo/irina#18]
Is there any plan to provide ES6 Promise compatibility to use with .then() instead of a callback?

**Comment by kasongoyo** [comment]
Hi @maticrivo . I am working on that feature and soon it will supported by this library if the admin will accept my pull request.

**Comment by kasongoyo** [comment]
Hi @maticrivo, find [this](https://github.com/kasongoyo/irina) for ES6 compatible version of this library

**Comment by lykmapipo** [comment]
@kasongoyo & @maticrivo Using nodejs callback style was by design. You can use any [promise library](http://bluebirdjs.com/docs/api/promise.promisify.html) to promisify callback style to return promises.

Hope it helps.
